// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3aGuZI3Tj3lTR-epA7-4Dck4E6T3MVU',
    appId: '1:1076138122667:web:35fe4a9491e9040cde86ee',
    messagingSenderId: '1076138122667',
    projectId: 'laza-750a8',
    authDomain: 'laza-750a8.firebaseapp.com',
    storageBucket: 'laza-750a8.firebasestorage.app',
    measurementId: 'G-CMEB5ZGKVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGKFsQOEgPApl01chICrYlsUpZAgpUDU',
    appId: '1:1076138122667:android:7b29ffd63eaf82eede86ee',
    messagingSenderId: '1076138122667',
    projectId: 'laza-750a8',
    storageBucket: 'laza-750a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiLLkR52K3CjkRmOn_KzcXiBv1AxDMcm8',
    appId: '1:1076138122667:ios:e4277e9fad9452edde86ee',
    messagingSenderId: '1076138122667',
    projectId: 'laza-750a8',
    storageBucket: 'laza-750a8.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiLLkR52K3CjkRmOn_KzcXiBv1AxDMcm8',
    appId: '1:1076138122667:ios:e4277e9fad9452edde86ee',
    messagingSenderId: '1076138122667',
    projectId: 'laza-750a8',
    storageBucket: 'laza-750a8.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd3aGuZI3Tj3lTR-epA7-4Dck4E6T3MVU',
    appId: '1:1076138122667:web:cf343113273b9cbcde86ee',
    messagingSenderId: '1076138122667',
    projectId: 'laza-750a8',
    authDomain: 'laza-750a8.firebaseapp.com',
    storageBucket: 'laza-750a8.firebasestorage.app',
    measurementId: 'G-C617SKT9QT',
  );
}
